drop table if exists endpoint_hit;

create table if not exists endpoint_hit
(
    id        bigint generated by default as identity
        primary key,
    app       varchar(64),
    uri       varchar,
    ip        varchar(39),
    timestamp timestamp
);

delete from endpoint_hit;
alter table endpoint_hit
alter column id
restart; 
