create table if not exists endpoint-hit
(
    id        bigint generated by default as identity
    primary key,
    app       varchar,
    uri       varchar,
    ip        varchar,
    timestamp timestamp
);


