version: '3.1'
services:

  stats-server:
    build:
      context: .
      dockerfile: stats-service/stats-server/Dockerfile
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore-with-me-stats
      - POSTGRES_USER=VanDarkholme
      - POSTGRES_PASSWORD=300bucks

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explore-with-me-stats
      - POSTGRES_USER=VanDarkholme
      - POSTGRES_PASSWORD=300bucks

  ewm-service:
    build:
      context: .
      dockerfile: main-service/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore-with-me-main
      - POSTGRES_USER=VanDarkholme
      - POSTGRES_PASSWORD=300bucks

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore-with-me-main
      - POSTGRES_USER=VanDarkholme
      - POSTGRES_PASSWORD=300bucks
